### ISSUE TITLE
New Relic API access must be enabled message

### ISSUE THREAD

**Issue by grtdevops** [jmezach/NewRelicDashboardWidgets#5]
Hi all,

We have 3 internal servers that are monitored as servers in our new relic account.
I have TFS dashboard that hosts new relic extensions (see below) that could fetch server's metrics from new relic API – using the new relic API key (of course).
**We recently moved to other New Relic re-seller (webiscope).** Right after we moved the accounts, I realized that my extensions are failing to approach the new relic servers. Naturally I re-generated API key and tried to set them up in the TFS extensions - BUT without any luck. I keep getting "_**New Relic API access must be enabled**_" error message in the widget configuration.

![image](https://cloud.githubusercontent.com/assets/21056815/23153946/f87ecd08-f813-11e6-949a-caf51fc81920.png)

Will appreciate any lead in this one.

Thanks in advance,
Ofer

**Comment by jmezach** [comment]
Hi there, thanks for reporting this issue. I've had a look through the code and looks like the error message you are seeing is only shown if the New Relic API returns a 403 forbidden. Could you try to use the [New Relic API explorer](https://rpm.newrelic.com/api/explore) and see if you can use the same API key there?

**Comment by grtdevops** [comment]
Thanks for the reply.
I got the following while trying to retrieve our servers:

_HTTP/1.1 403 Forbidden
Content-Type: application/json
Cache-Control: no-cache
{
  "error": {
    "title": "New Relic API access has not been enabled for this account."
  }
}_

**It looks like the vendor itself should have enabled the API access.**
Anyways, we are going to be back to the original vendor, where API access has worked properly.

Thanks again,
Ofer

**Comment by jmezach** [comment]
Yeah, I think this isn't something I can fix for you. Please let me know if you require further assistance with this. I'm closing the issue for now.

**Comment by grtdevops** [comment]
Thanks you.
